### PR TITLE
remember the color of the note when refreshed

### PR DESCRIPTION
**Pull request by yamitrvg12**

### CODE REVIEW

**Review by ArunBohra12 — COMMENTED** [review]
Hi @yamitrvg12,

Can you explain why did you remove the type module from app.js in the HTML?
Currently, we are using vite and it requires the js files that you put into HTML to be modules.

If you took a look at the production [notem.ml](https://www.notem.ml/), it's not working and in the console, we have the following error:

image

**Comment by aditya-singh9** [comment]
I have updated it, please check once

**Comment by ArunBohra12** [comment]
It still doesn't work as we have these functions from js files,

image
These functions will be undefined when the onclick happens.
And in JS, modules don't work like this, we should have these function bindings inside of a JS module.

**Comment by aditya-singh9** [comment]
Then please fix this issue by opening a new issue

**Comment by yamitrvg12** [comment]
Hi [ArunBohra12](https://github.com/ArunBohra12), for some reason when we used 'modules' the changeTheme function does not work. So if it required that we need to add the modules, i know how to fixed :)
I am going to make the changes, give me a couple minutes to do that :)

working on it...

**Comment by ArunBohra12** [comment]
@yamitrvg12 It doesn't work because you must import functions from modules you can't use like js scripts. [Read differences here](https://stackoverflow.com/questions/39652618/classic-scripts-vs-module-scripts-in-javascript)

And we need modules as we need to build the app. Please make sure that you run `npm run build` and then `npm run preview`. And once that success then only you can push without errors.

**Comment by yamitrvg12** [comment]
@ArunBohra12 Could you please take a look again https://github.com/aditya-singh9/notem/pull/20

image

**Comment by ArunBohra12** [comment]
Seems ok to me. I left review #20 
If you want to do that just update the pull req instead of adding another one

**Pull request merged**
