### PR TITLE
navbar 

### PR DESCRIPTION
**Pull request by makoteq**
### **Issue: #5** 
 **List of changes:**
- Brand new navbar
- Added cursor interaction to circles in top-left part of the page
- Added icon with hyperlink to this repository
- Created "assets" folder

### [Demo](https://makoteq.github.io/notem/)

### CODE REVIEW

**Comment by makoteq** [comment]
hacktoberfest label would be great!

**Comment by makoteq** [comment]
something wrong?

**Comment by makoteq** [comment]
@aditya-singh9

**Comment by aditya-singh9** [comment]
iguess hacktoberfest-accepted label would do your work, and personally i didnt like the navbar.

**Pull request closed without merging**
