### PR TITLE
Add navbar

### PR DESCRIPTION
**Pull request by NalinPlad**
re pull req after i fixed merge conflicts

### CODE REVIEW

**Comment by NalinPlad** [comment]
Screen Shot 2022-10-03 at 1 32 50 PM

**Comment by NalinPlad** [comment]
You can also check it out using the vercel bot above the image

**Comment by aditya-singh9** [comment]
Can you remove the "notem" and "help".
And put the theme buttons on left.

And about github, add an icon of github, instead of the words, on the right.

And add one more icon of hammer with a link of my  portfolio [website](www.adityasingh.tech) on the left of github

Like the order should be 
Theme...................hammer github

**Comment by NalinPlad** [comment]
alright i changed it
Screen Shot 2022-10-04 at 9 51 58 AM

**Comment by NalinPlad** [comment]
Also yes I know the hammer and the github logo are mixed up I already changed it to the right order

**Pull request merged**
