### PR TITLE
Delete .index.html.swp

### PR DESCRIPTION
**Pull request by NalinPlad**
Un needed swap file from vim

### CODE REVIEW

**Comment by NalinPlad** [comment]
I accidentally added it with the previous pull request

**Comment by aditya-singh9** [comment]
> Please do not make these kinds of prs and make some useful prs which are adding features to the functionality of the website.
You can just point these mistakes by openeing an issue

As you have made some useful prs, i will not add the spam label to it

**Comment by NalinPlad** [comment]
Did you read my comment? 

Swap (.swp) files are automatically generated by vim (a code editor) when editing files. They are not useful for the github repo and are just clutter. 

https://unix.stackexchange.com/questions/27923/what-causes-swap-files-to-be-created

I accidentally added this file in my previous pull request https://github.com/aditya-singh9/notem/pull/21

it needs to be deleted!!

**Comment by NalinPlad** [comment]
**you can see in the vercel deployment that this does not affect the app at all**

**Comment by NalinPlad** [comment]
but thank you fore letting me know that I should have just opened an issue 👍

**Pull request closed without merging**
